### ISSUE TITLE
OVAL Lint-like tool

### ISSUE THREAD

**Issue by isimluk** [OpenSCAP/openscap#192]
Rationale: The authors of security policies sometimes struggle with OVAL language. There are certain statements which are valid by OVAL standard, but are not efficient or equals to no-operation.

Deliverable: A command-line tool or `oscap oval lint` module. The tool will inspect single OVAL file and report errors and warnings. A lot can be achieved by coding schematron-like XSLT. 

This is big idea.

**Comment by GaryGapinski** [comment]
This is an interesting idea.  There are indeed many ways to err when crafting OVAL documents. I have some experience making such errors. The language lends itself to the task.

I will volunteer an example for consideration. Many more come to mind.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<oval_definitions xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5" xmlns:oval="http://oval.mitre.org/XMLSchema/oval-common-5"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://oval.mitre.org/XMLSchema/oval-definitions-5 file:/dev/urandom  http://oval.mitre.org/XMLSchema/oval-common-5 file:/dev/zero">
   <!-- xsi:schemaLocation is overrated and frequently misused. Use XML Catalog instead. -->
   <generator>
      <oval:product_name>Devil's Repository</oval:product_name>
      <oval:product_version>eternal and unbounded</oval:product_version>
      <oval:schema_version>5.11.1</oval:schema_version>
      <oval:timestamp>2015-12-24T10:49:10.867-05:00</oval:timestamp>
   </generator>
   <definitions>
      <definition id="oval:us.iffy.oval:def:1" version="1" class="miscellaneous">
         <metadata>
            <title>😈1</title>
            <description>🙈🙉🙊</description>
         </metadata>
         <criteria operator="AND">
            <extend_definition definition_ref="oval:us.iffy.oval:def:2" comment="Veselé Vánoce!"/>
            <criterion test_ref="oval:us.iffy.oval:tst:1" comment="Neužitečný znalostí."/>
         </criteria>
      </definition>
      <definition id="oval:us.iffy.oval:def:2" version="1" class="miscellaneous">
         <metadata>
            <title>😈2</title>
            <description>🙈🙉🙊</description>
         </metadata>
         <criteria operator="AND" negate="true" comment="Nechci, aby neuvedl nepravda.">
            <extend_definition definition_ref="oval:us.iffy.oval:def:1" comment="Neužitečný znalostí."/>
            <criterion test_ref="oval:us.iffy.oval:tst:1" comment="Neužitečný znalostí."/>
         </criteria>
      </definition>
   </definitions>
   <tests>
      <variable_test xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#independent" id="oval:us.iffy.oval:tst:1" version="1" check="all"
         comment="Neužitečný znalostí."
         xsi:schemaLocation="http://oval.mitre.org/XMLSchema/oval-definitions-5#independent https://nvd.nist.gov/schema/nvdcve_1.2.1.xsd">
         <!-- xsi:schemaLocation is overrated and frequently misused. Use XML Catalog instead. -->
         <object object_ref="oval:us.iffy.oval:obj:1"/>
      </variable_test>
   </tests>
   <objects>
      <variable_object xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#independent" id="oval:us.iffy.oval:obj:1" version="1"
         comment="Neužitečný znalostí.">
         <var_ref>oval:us.iffy.oval:var:1</var_ref>
      </variable_object>
   </objects>
   <variables xsi:schemaLocation="http://oval.mitre.org/XMLSchema/oval-definitions-5 https://nvd.nist.gov/schema/nvdcve_1.2.1.xsd">
      <local_variable id="oval:us.iffy.oval:var:1" datatype="string" version="1" comment="Není nic zajímavého sem.">
         <variable_component var_ref="oval:us.iffy.oval:var:2"/>
      </local_variable>
      <local_variable id="oval:us.iffy.oval:var:2" datatype="string" version="1" comment="Proč hledáte tady?">
         <variable_component var_ref="oval:us.iffy.oval:var:3"/>
      </local_variable>
      <local_variable id="oval:us.iffy.oval:var:3" datatype="string" version="1" comment="Nechci říkat nepravdu.">
         <variable_component var_ref="oval:us.iffy.oval:var:1"/>
      </local_variable>
      <local_variable id="oval:us.iffy.oval:var:4" datatype="string" version="1" comment="Někdy jiný jazyk může udělat obtížný výraz snadnější prohlásit.">
         <concat>
            <object_component object_ref="oval:us.iffy.oval:obj:1" item_field="value"/>
            <variable_component var_ref="oval:us.iffy.oval:var:1"/>
         </concat>
      </local_variable>
   </variables>
</oval_definitions>
```
I believe some suitable array of "languages" to replace OVAL would be appropriate. An essential aspect of such would be extensibility — currently absent in the SCAP-related languages.

**Comment by jan-cerny** [comment]
@GaryGapinski Thanks for this great example with funny Czech translations :+1: 

 I have tried what will happen when I evaluate these OVAL definitions using OpenSCAP. Unfortunately, I have discovered that OpenSCAP has no detection of recursive references. It simply tried to evaluate the test again and again and finally it gave a very nice segfault. :-)
```
#0  0x00007f4d1606d8ac in _int_malloc () from /lib64/libc.so.6
#1  0x00007f4d1606f970 in malloc () from /lib64/libc.so.6
#2  0x00007f4d18a87ee9 in __oscap_alloc (s=s@entry=8) at alloc.c:52
#3  0x00007f4d18ab55e3 in oval_collection_iterator (collection=0x19df780) at oval_collection.c:125
#4  0x00007f4d18aa105b in oval_probe_query_criteria (sess=sess@entry=0x19df2d0, cnode=<optimized out>) at oval_probe.c:431
#5  0x00007f4d18aa1078 in oval_probe_query_criteria (sess=sess@entry=0x19df2d0, cnode=<optimized out>) at oval_probe.c:438
....
....
....
#104776 0x00007f4d18aa1078 in oval_probe_query_criteria (sess=sess@entry=0x19df2d0, cnode=<optimized out>) at oval_probe.c:438
#104777 0x00007f4d18aa1078 in oval_probe_query_criteria (sess=0x19df2d0, cnode=<optimized out>) at oval_probe.c:438
#104778 0x00007f4d18aa13d3 in oval_probe_query_definition (sess=<optimized out>, id=id@entry=0x19df940 "oval:us.iffy.oval:def:2")
    at oval_probe.c:353
#104779 0x00007f4d18a952c1 in oval_agent_eval_definition (ag_sess=0x19de3c0, id=0x19df940 "oval:us.iffy.oval:def:2") at oval_agent.c:174
#104780 0x00007f4d18a9543a in oval_agent_eval_system (ag_sess=0x19de3c0, cb=cb@entry=0x409b90 <app_oval_callback>, arg=arg@entry=0x0)
    at oval_agent.c:270
#104781 0x00007f4d18a9632f in oval_session_evaluate (session=session@entry=0x19cf7f0, probe_root=<optimized out>, 
    fn=fn@entry=0x409b90 <app_oval_callback>, arg=arg@entry=0x0) at oval_session.c:372
#104782 0x0000000000409b7f in app_evaluate_oval (action=0x7fff7b9337f0) at oscap-oval.c:383
#104783 0x0000000000407e0e in oscap_module_call (action=0x7fff7b9337f0) at oscap-tool.c:261
#104784 oscap_module_process (module=0x615060 <OVAL_EVAL>, module@entry=0x614a20 <OSCAP_ROOT_MODULE>, argc=argc@entry=4, 
    argv=argv@entry=0x7fff7b933a88) at oscap-tool.c:346
#104785 0x0000000000406eaf in main (argc=4, argv=0x7fff7b933a88) at oscap.c:80

```

So I wonder whether it is possible to have a run-time check of similar constructs in OpenSCAP to avoid crashes. I am interested in implementing this kind of check.

**Comment by yuumasato** [comment]
This is very interesting and big. It would surely help the community.

**Comment by isimluk** [comment]
Thanks and here is a suggestion.

Scap-security-guide has great community of contributors who maintain sometimes quite complex checks, they may have ideas what a liner could assert and why. 

People, however, struggle to remember what these OVAL quirks are, when you ask them. Although, they may be able to write a suggestion that comes to their mind as they go when they dispatch their duties and figure out an OVAL quirk here and there.

Is there a way to make it easy for SSG community to start building this knowledge?
