### ISSUE TITLE
oscap-docker tracebacks when invoked with invalid image ID

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/openscap#317]
Hello, I have encountered an traceback with oscap-docker 1.2.8 on Fedora 23.
I run the command with a nonsense image  ID.
```
[jcerny@thinkpad utils{issue303}]$ sudo oscap-docker image-cve dasdasdasd
Traceback (most recent call last):
  File "/bin/oscap-docker", line 108, in <module>
    args.func()
  File "/bin/oscap-docker", line 44, in cve_scan
    result = OS.scan_cve(self.args.scan_target, self.unknown_args)
  File "/usr/lib/python3.4/site-packages/oscap_docker_python/oscap_docker_util.py", line 193, in scan_cve
    _tmp_mnt_dir = DM.mount(image)
  File "/usr/lib/python3.4/site-packages/Atomic/mount.py", line 312, in mount
    driver_mount_fn(identifier, options)
  File "/usr/lib/python3.4/site-packages/Atomic/mount.py", line 346, in _mount_devicemapper
    cid = self._identifier_as_cid(identifier)
  File "/usr/lib/python3.4/site-packages/Atomic/mount.py", line 276, in _identifier_as_cid
    ''.format(identifier))
Atomic.mount.MountError: dasdasdasd did not match any image or container.
```

**Comment by jan-cerny** [comment]
Fixed in https://github.com/OpenSCAP/openscap/pull/336
