### ISSUE TITLE
oscap-docker scan failed

### ISSUE THREAD

**Issue by dongtaofei** [OpenSCAP/openscap#711]
Hi, I just try to use oscap-docker to scan docker images.
and using rehl7 image:
```
docker images
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
registry.access.redhat.com/rhel7   latest              41a4953dbf95        4 weeks ago         192.5 MB
```

```
docker ps
CONTAINER ID        IMAGE                              COMMAND             CREATED             STATUS              PORTS               NAMES
29810d5a69b7        registry.access.redhat.com/rhel7   "/bin/bash"         About an hour ago   Up 46 minutes                           our-rhel7-container
```

and got this:
```
oscap-docker container 29810d5a69b7

Command: oscap failed!
Command returned exit code 101.
Usage:    oscap [options] module operation [operation-options-and-arguments]
Commands: ds oval xccdf cvss cpe cve info
Help:     oscap -h

Traceback (most recent call last):
  File "/usr/bin/oscap-docker", line 112, in <module>
    args.func()
  File "/usr/bin/oscap-docker", line 51, in scan
    result = OS.scan(self.args.scan_target, self.unknown_args)
  File "/usr/lib/python2.7/site-packages/oscap_docker_python/oscap_docker_util.py", line 264, in scan
    sys.stdout.write(self.helper._scan(chroot, scan_args))
  File "/usr/lib/python2.7/site-packages/oscap_docker_python/oscap_docker_util.py", line 150, in _scan
    return self.oscap_chroot("foo", "bar", chroot, *tmp_tuple)
  File "/usr/lib/python2.7/site-packages/oscap_docker_python/oscap_docker_util.py", line 130, in oscap_chroot
    self._cleanup_by_path(chroot_path)
  File "/usr/lib/python2.7/site-packages/oscap_docker_python/oscap_docker_util.py", line 176, in _cleanup_by_path
    DM._clean_temp_container_by_path(_no_rootfs)
  File "/usr/lib/python2.7/site-packages/Atomic/mount.py", line 714, in _clean_temp_container_by_path
    self.d.remove_container(short_cid)
  File "/usr/lib/python2.7/site-packages/Atomic/client.py", line 58, in newfunc
    result = attr(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/container.py", line 293, in remove_container
    self._raise_for_status(res)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 173, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("{"message":"No such container: tmpRkSJmp"}")
```

```
oscap-docker image registry.access.redhat.com/rhel7

Command: oscap failed!
Command returned exit code 101.
Usage:    oscap [options] module operation [operation-options-and-arguments]
Commands: ds oval xccdf cvss cpe cve info
Help:     oscap -h

Traceback (most recent call last):
  File "/usr/bin/oscap-docker", line 112, in <module>
    args.func()
  File "/usr/bin/oscap-docker", line 51, in scan
    result = OS.scan(self.args.scan_target, self.unknown_args)
  File "/usr/lib/python2.7/site-packages/oscap_docker_python/oscap_docker_util.py", line 264, in scan
    sys.stdout.write(self.helper._scan(chroot, scan_args))
  File "/usr/lib/python2.7/site-packages/oscap_docker_python/oscap_docker_util.py", line 150, in _scan
    return self.oscap_chroot("foo", "bar", chroot, *tmp_tuple)
  File "/usr/lib/python2.7/site-packages/oscap_docker_python/oscap_docker_util.py", line 130, in oscap_chroot
    self._cleanup_by_path(chroot_path)
  File "/usr/lib/python2.7/site-packages/oscap_docker_python/oscap_docker_util.py", line 176, in _cleanup_by_path
    DM._clean_temp_container_by_path(_no_rootfs)
  File "/usr/lib/python2.7/site-packages/Atomic/mount.py", line 714, in _clean_temp_container_by_path
    self.d.remove_container(short_cid)
  File "/usr/lib/python2.7/site-packages/Atomic/client.py", line 58, in newfunc
    result = attr(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/container.py", line 293, in remove_container
    self._raise_for_status(res)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 173, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("{"message":"No such container: tmpIuYTYW"}")
```

Do you have idea?

BR/Taofei

**Comment by dongtaofei** [comment]
oscap -V
OpenSCAP command line tool (oscap) 1.2.10
Copyright 2009--2016 Red Hat Inc., Durham, North Carolina.

==== Supported specifications ====
XCCDF Version: 1.2
OVAL Version: 5.11.1
CPE Version: 2.3
CVSS Version: 2.0
CVE Version: 2.0
Asset Identification Version: 1.1
Asset Reporting Format Version: 1.1

==== Capabilities added by auto-loaded plugins ====
No plugins have been auto-loaded...

==== Paths ====
Schema files: /usr/share/openscap/schemas
Default CPE files: /usr/share/openscap/cpe
Probes: /usr/libexec/openscap

==== Inbuilt CPE names ====
Red Hat Enterprise Linux - cpe:/o:redhat:enterprise_linux
......

and 
docker version
Client:
 Version:         1.12.5
 API version:     1.24
 Package version: docker-common-1.12.5-14.el7.x86_64
 Go version:      go1.7.4
 Git commit:      047e51b/1.12.5
 Built:           Wed Jan 11 17:53:20 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.5
 API version:     1.24
 Package version: docker-common-1.12.5-14.el7.x86_64
 Go version:      go1.7.4
 Git commit:      047e51b/1.12.5
 Built:           Wed Jan 11 17:53:20 2017
 OS/Arch:         linux/amd64

python -V
Python 2.7.5

**Comment by mpreisler** [comment]
You aren't using the right command line arguments. Either use `image-cve` instead of just `image` or add the rest of the necessary command line arguments.

Check out `man oscap-docker` for more info.

**Comment by dongtaofei** [comment]
Hi, 
I tried to use image-cve and container-cve and got same result:
oscap-docker image-cve registry.access.redhat.com/rhel7

Command: oscap oval eval --id oval:org.open-scap.cpe.rhel:def:7 /usr/share/openscap/cpe/openscap-cpe-oval.xml 2>&1 > /dev/null failed!
Command returned exit code 1.
FAIL: 291:chdir: 2, No such file or directory
W: oscap: Can't receive message: 2, No such file or directory.
E: oscap: Can't close sd: 10, No child processes.
E: oscap: Recv: retry limit (0) reached.
OpenSCAP Error: Unable to close probe sd [oval_probe_ext.c:424]
Unable to receive a message from probe [oval_probe_ext.c:579]
Failed to create a new agent session. [oval_session.c:320]

Warning: umount: /tmp/tmp84Lb_8: not mounted

Retrying 1/10 to unmount /tmp/tmp84Lb_8

BR/Taofei

**Comment by dongtaofei** [comment]
Hi,
I tried to different combination, all are failed. I used image-cve and container-cve with oval, xccdf,
I cannot make it work for me. I re-install in other server and got same result.

BR/Taofei

**Comment by yuumasato** [comment]
@dongtaofei  full command to run oscap-docker would be something like this:

`# oscap-docker image 41a4953dbf95 xccdf eval --profile xccdf_org.ssgproject.content_profile_pci-dss --results results.xml --report report.hml /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml`

Where `41a4953dbf95` is the Image ID of your container image returned by `docker images` command.

you can see available profiles by running:
`$ oscap info /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml`

And `image-cve` and `container-cve` dont require oval or xccdf arguments, just run:
`# oscap-docker image-cve 41a4953dbf95`

This page can give you some more details:
https://www.open-scap.org/resources/documentation/security-compliance-of-rhel7-docker-containers/

**Comment by dongtaofei** [comment]
HI,

I tried it, it is still same result:
docker images
REPOSITORY                                  TAG                 IMAGE ID            CREATED             SIZE
registry.access.redhat.com/rhel7            latest              41a4953dbf95        4 weeks ago         192.5 MB

oscap-docker image-cve 41a4953dbf95

Command: oscap oval eval --id oval:org.open-scap.cpe.rhel:def:7 /usr/share/openscap/cpe/openscap-cpe-oval.xml 2>&1 > /dev/null failed!
Command returned exit code 1.
FAIL: 291:chdir: 2, No such file or directory
W: oscap: Can't receive message: 2, No such file or directory.
E: oscap: Can't close sd: 10, No child processes.
E: oscap: Recv: retry limit (0) reached.
OpenSCAP Error: Unable to close probe sd [oval_probe_ext.c:424]
Unable to receive a message from probe [oval_probe_ext.c:579]
Failed to create a new agent session. [oval_session.c:320]

Warning: umount: /tmp/tmp8pxLmF: not mounted

Retrying 1/10 to unmount /tmp/tmp8pxLmF
Warning: umount: /tmp/tmp8pxLmF: not mounted

oscap-docker image 41a4953dbf95 xccdf eval --profile xccdf_org.ssgproject.content_profile_pci-dss --results results.xml --report report.hml /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml

Command: oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_pci-dss --results results.xml --report report.hml /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml failed!
Command returned exit code 1.
WARNING: This content points out to the remote resources. Use `--fetch-remote-resources' option to download them.
WARNING: Skipping http://www.redhat.com/security/data/oval/Red_Hat_Enterprise_Linux_7.xml file which is referenced from XCCDF content
FAIL: 291:chdir: 2, No such file or directory
W: oscap: Can't receive message: 2, No such file or directory.
E: oscap: Can't close sd: 10, No child processes.
E: oscap: Recv: retry limit (0) reached.
OpenSCAP Error: Unable to close probe sd [oval_probe_ext.c:424]
Unable to receive a message from probe [oval_probe_ext.c:579]
Failed to create new OVAL agent session for: 'ssg-rhel7-oval.xml'. [xccdf_session.c:919]

Traceback (most recent call last):
  File "/usr/local/bin/oscap-docker", line 112, in <module>
    args.func()
  File "/usr/local/bin/oscap-docker", line 51, in scan
    result = OS.scan(self.args.scan_target, self.unknown_args)
  File "/usr/lib/python2.7/site-packages/oscap_docker_python/oscap_docker_util.py", line 264, in scan
    sys.stdout.write(self.helper._scan(chroot, scan_args))
  File "/usr/lib/python2.7/site-packages/oscap_docker_python/oscap_docker_util.py", line 150, in _scan
    return self.oscap_chroot("foo", "bar", chroot, *tmp_tuple)
  File "/usr/lib/python2.7/site-packages/oscap_docker_python/oscap_docker_util.py", line 130, in oscap_chroot
    self._cleanup_by_path(chroot_path)
  File "/usr/lib/python2.7/site-packages/oscap_docker_python/oscap_docker_util.py", line 176, in _cleanup_by_path
    DM._clean_temp_container_by_path(_no_rootfs)
  File "/usr/lib/python2.7/site-packages/Atomic/mount.py", line 714, in _clean_temp_container_by_path
    self.d.remove_container(short_cid)
  File "/usr/lib/python2.7/site-packages/Atomic/client.py", line 58, in newfunc
    result = attr(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/container.py", line 293, in remove_container
    self._raise_for_status(res)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 173, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("{"message":"No such container: tmpaLAMP9"}")


I got one script from Simon, it works partially.
Here are the script and one from python script coming with openscap under /usr/local/bin

BR/Taofei
